services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=splearn'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=spring'
    ports:
      - '3306:3306'
